# Generated by Django 4.2.7 on 2023-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storestatus",
            name="store_id",
            field=models.CharField(max_length=20),
        ),
    ]
