# Generated by Django 4.2.7 on 2023-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_monitoring", "0004_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=50, unique=True)),
                ("store_id", models.CharField(max_length=20)),
                ("uptime_last_hour", models.IntegerField()),
                ("uptime_last_day", models.IntegerField()),
                ("uptime_last_week", models.IntegerField()),
                ("downtime_last_hour", models.IntegerField()),
                ("downtime_last_day", models.IntegerField()),
                ("downtime_last_week", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
